# Generated by Django 4.1.4 on 2023-05-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='dni_medico',
            field=models.CharField(default='', max_length=9),
        ),
    ]
